<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0 " />
		<style>
		body{
			
		}
		a{
			color:#45818e;
		}
		h2, h3{
			color:#3f909f;
			padding-left:10px;
		}
		p{
			padding:10px;
		}
		.h3-sub-footer{
			font-size:1em;
		}
		.div-sub-footer{
			background-color:#d9ead3;
			color:#311f15;
		}
		.p-sub-footer{
			font-size:.8em;
			padding:10px;
			margin:0;
			background-color: #d9ead3;
			color: #311f15;
		}
		.p-sub-footer a{
			color:#311f15;
		}
		</style>
	</head>
		<body class="em_body" style="margin:0px; padding:0px;">
		<h2>$email.Subject$</h2>